apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../providers/provider-aws-config.yaml
  - ../providers/provider-aws-iam.yaml
  - ../providers/provider-s3.yaml
  - ../providers/provider-ec2.yaml
  - ../providers/provider-eks.yaml
  - ../s3/bucket.yaml
  - ../s3/bucketversioning.yaml
  - ../vpc/igw.yaml
  - ../vpc/natgw.yaml
  - ../vpc/routes.yaml
  - ../vpc/subnets.yaml