apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kelvinskell/crossplane-argocd.git'
    targetRevision: main
    path: crossplane
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      